### ISSUE TITLE
Predicting Camera Location

### ISSUE THREAD

**Issue by Zumbalamambo** [vislearn/ngdsac_horizon#2]
Is it possible to use this technique to localize the camera in the 3d space?

**Comment by ebrach** [comment]
The horizon certainly constrains the camera pose, e.g. you could calculate pitch and roll angles directly from the horizon but in general this code would not allow you to infer the complete 6D camera pose. We applied NG-RANSAC also to absolute camera pose estimation, please check the paper for that (linked in the readme). The corresponding code is not online yet, but should be up within the next few weeks.
