### ISSUE TITLE
Hi, sorry for bothering you. Is the HLW Dataset still available?

### ISSUE THREAD

**Issue by FIR2022start** [vislearn/ngdsac_horizon#3]
Hi, sorry for bothering you. Is the HLW Dataset still available?

**Comment by ebrach** [comment]
It seems the access is more restrictive than it was when I uploaded this code. Thanks for bringing it up. It seems you can request access via this form: https://docs.google.com/forms/d/e/1FAIpQLSdQQrewZj8jnHihKKdyZ22H4Zw6YxbUHBPddIpgbGfmCxZypQ/viewform

Hope that works!

**Comment by ebrach** [comment]
I changed the readme accordingly.

**Comment by FIR2022start** [comment]
Got it, thank you very much!
